kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "cat-scanner.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: longhorn
