name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main

  deploy:
    needs:
      - package
    runs-on: [k8s-internal]
    container:
      image: registry.gitlab.com/cmmarslender/kubectl-helm:v3.9.0
    steps:
      - uses: actions/checkout@v2

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            secret/data/fmt/k8s/ghcr_image_pull username | IMAGE_PULL_USERNAME;
            secret/data/fmt/k8s/ghcr_image_pull password | IMAGE_PULL_PASSWORD;
            secret/data/fmt/k8s/fremont-baremetal api_server_url | K8S_API_SERVER_URL;
            secret/data/keybase/chia_network.testalerts webhook | KEYBASE_WEBHOOK_URL;

      - name: Login to k8s cluster
        uses: Chia-Network/actions/vault/k8s-login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ env.VAULT_TOKEN }}
          backend_name: fremont-baremetal
          role_name: github-actions
          cluster_url: ${{ env.K8S_API_SERVER_URL }}

      - uses: Chia-Network/actions/k8s/image-pull-secret@main
        with:
          secret_name: cat-scanner-image-pull
          namespace: cat-scanner
          username: ${{ env.IMAGE_PULL_USERNAME }}
          password: ${{ env.IMAGE_PULL_PASSWORD }}
          docker_server: "ghcr.io"

      - uses: Chia-Network/actions/helm/deploy@main
        env:
          DOCKER_TAG: sha-${{ github.sha }}
        with:
          namespace: cat-scanner
          app_name: cat-scanner
          helm_chart: "./k8s/cat-scanner"
          helm_values: "./k8s/values/mainnet.yaml"
